### ISSUE TITLE
[Poplar] - Android 8.1 - long delay establishing cellular connectivity on boot

### ISSUE THREAD

**Issue by icefalcon2225** [sonyxperiadev/bug_tracker#141]
**Platform:**  yoshino
**Device:**  Xperia XZ1 G8342 (poplar)
**Kernel version:**  4.4.132-g8ac884e-dirty
**Android version:**  8.1.0_r26 OPM2.171019.029.B1

**Description**
When the device powers up, it takes more than 2 minutes after the Android UI loads before the phone establishes cellular connectivity.  This only happens when using the AOSP image --- with the factory image, the SIM is available as soon as Android loads.  This seems to indicate that the hardware, radio, and SIM are okay, but that there might be an issue in the AOSP source for the Xperia XZ1.

**Symptoms**
The device takes over 2 minutes after Android has loaded to establish cellular connectivity on each boot.

**How to reproduce**
Here are the steps that reproduce the issue:

   - Flash a fresh AOSP image on the device.  

   - Put a SIM card in the device before powering it on.  I was using a GSM SIM (T-Mobile) in the normal slot (not the slot which can also hold an SD card).

   - Power on the device
 
   - On the first boot after flashing, the following dialog box appears:

```
Update preferred SIM card?
"CARD 1 is the only SIM in your device.  Do you want to use this SIM for mobile data, calls, and SMS messages? "
 (NO/YES)
```

After selecting YES, a toast pops which states "Switching data SIM, this may take up to a minute...".  As the toast indicates it can be a minute or more before cellular connectivity is established.

   - On subsequent boots, there is no dialog asking to update the preferred SIM card anymore.  However, it still takes a significant amount of time (often in the 2.5 minute range) to establish cellular connectivity each boot.  This illustrates the primary issue.

Some notes: 

   - Trying to use the SIM to make a call during the time when connectivity isn't established yet pops an error dialog which states "Turn off airplane mode to make a call.".

   - Once the device successfully establishes cellular connectivity (after 2.5 minutes), the SIM appears to work properly.

   - I tried using two SIMs in the phone (e.g., a SIM in both slots) thinking that it might be the empty SIM slot that was causing a problem, but the device still had the 2.5+ minute delay to establish connect connectivity even with two SIMs in it

Is it possible to fix (remove) this long wait for cellular connectivity on the AOSP image for the Xperia XZ1?

**Attached files**
I've attached three files:
   - *kmsg_aosp.txt* --- the kmsg from an AOSP boot, captured right after the device showed that it had cellular connectivity (about 3 minutes after Android booted).  This is not the first boot after flashing, so there is no "preferred SIM" dialog.
   - *logcat_aosp.txt* --- the logcat from an AOSP boot, captured right after the device showed that it had cellular connectivity (about 3 minutes after Android booted).  This is not the first boot after flashing, so there is no "preferred SIM" dialog.
   - *logcat_factory.txt* --- the logcat from a factory boot, captured right after the device booted and showed that it had cellular connectivity.  The same SIM was used as in the AOSP logs.

[kmsg_aosp.txt](https://github.com/sonyxperiadev/bug_tracker/files/2141896/kmsg_aosp.txt)
[logcat_aosp.txt](https://github.com/sonyxperiadev/bug_tracker/files/2141897/logcat_aosp.txt)
[logcat_factory.txt](https://github.com/sonyxperiadev/bug_tracker/files/2141898/logcat_factory.txt)

**Comment by jerpelea** [comment]
the issue has been fixed and the fix will come on vendor v13 
thanks for reporting the issue

**Comment by jerpelea** [comment]
@icefalcon2225 icefalcon2225 please test the new binaries

**Comment by icefalcon2225** [comment]
I tested the issue, using the v13 binaries and the 8.1.0_r35 source.  I also tried it with the v13 binaries and the 8.1.0_r30 source.  Neither build fixed the issue.

I've included the logs from a boot of the device built from the 8.1.0_r35 source and using the v13 binaries.  Similar to before, the device boots and quickly detects the SIM card, but there is no cellular connectivity for about 2.5 minutes.  During this time, the cellular signal strength triangle is showing but empty.  After the 2.5 minute wait, the triangle fills and cellular connectivity is established --- at that point, I can make/receive calls and send/receive text messages.  The logs are taken from right after the cellular connectivity is established.

Let me know if you need any additional information.  Thank you.

[kmsg_v13_r35.txt](https://github.com/sonyxperiadev/bug_tracker/files/2177893/kmsg_v13_r35.txt)
[logcat_v13_r35.txt](https://github.com/sonyxperiadev/bug_tracker/files/2177894/logcat_v13_r35.txt)

**Comment by jerpelea** [comment]
@icefalcon2225 please try the following:
1. flash your device with the latest SW using flashtool and boot the device with it
https://developer.sony.com/develop/open-devices/get-started/flash-tool/

2. flash AOSP and test the network functionality using v14 binaries

**Comment by icefalcon2225** [comment]
I updated the factory image as you suggested, and then tried the AOSP image using the v14 binaries.  Unfortunately, this didn't fix the issue.

**My original factory image:**
   Android version:  8.0.0
   Build number: 47.1.A.2.281
   Kernel version:  4.4.74-perf+
   Baseband version: 8998-8998.gen.prodQ-00147-03

**After the update, the factory image is:**
   Android version:  8.0.0
   Build number: 47.1.A.12.235
   Kernel version:  4.4.78-perf+
   Baseband version: 8998-8998.gen.prodQ-00197-28

**The AOSP image is android-8.1.0_r35 with the v14 binaries:**
   Android version:  8.1.0
   Build number:  aosp_g8342-userdebug 8.1.0 OPM2.171026.006.G1
   Kernel version:  4.4.139-g880676b-dirty
   Baseband version: 8998-8998.gen.prodQ-00197-00 

Similar to before, the SIM works fine in the factory image --- the device has cellular connectivity around the time that the Android UI comes up.  With the AOSP image, the SIM icon at the top of the phone changes from the "no SIM" icon to the "empty triangle" (no connectivity) icon right as the Android UI comes up.  After that, however, it consistently takes about 2.5 minutes for the "empty triangle" icon to also say "LTE" and fill in.  That's the point when cellular connectivity is available.  I'm using the same T-Mobile SIM and same phone for both the factory and AOSP tests.

Here are the logs for the factory and AOSP boots, taken right after the cellular connectivity is established.

[logcat_factory_47.1.A.12.235.txt](https://github.com/sonyxperiadev/bug_tracker/files/2243328/logcat_factory_47.1.A.12.235.txt)
[kmsg_aosp_v14_r35.txt](https://github.com/sonyxperiadev/bug_tracker/files/2243329/kmsg_aosp_v14_r35.txt)
[logcat_aosp_v14_r35.txt](https://github.com/sonyxperiadev/bug_tracker/files/2243330/logcat_aosp_v14_r35.txt)

Thanks for your help so far.  Let me know if there is any other information that I can provide or tests that I can run to help debug the issue

**Comment by jerpelea** [comment]
@icefalcon2225 We released the US Customized SW
Please try the following :
1.flash 47.1.A.12.235 Customized US software on your device then boot the phone with this software 
2.flash AOSP and test the functionality

**Comment by icefalcon2225** [comment]
I updated the factory image using the "G8342 47.1.A.12.235 Customized_US 1310-4358 R6B" image (previously, I had used the "G8342 47.1.A.12.235 Customized_CE1 1310-4354 R7B" image), and then tried the AOSP image using the v14 binaries. Unfortunately, it still shows the same behavior (~2.5 minute delay in cellular connectivity).

On the first boot of the updated factory image, a dialog appeared that said "Your device will now restart to be optimized for your network operator.".  That's the first time that I remember seeing that dialog appear.

I also tried an AT&T SIM this time, in addition to the T-Mobile SIM that I've been testing with.  Both exhibit the same problem.

Here are the logs for the factory and AOSP boots, taken right after the cellular connectivity is established.

[logcat_factory_47.1.A.12.235_us.txt](https://github.com/sonyxperiadev/bug_tracker/files/2246101/logcat_factory_47.1.A.12.235_us.txt)
[kmsg_aosp_v14_r35_us.txt](https://github.com/sonyxperiadev/bug_tracker/files/2246102/kmsg_aosp_v14_r35_us.txt)
[logcat_aosp_v14_r35_us.txt](https://github.com/sonyxperiadev/bug_tracker/files/2246103/logcat_aosp_v14_r35_us.txt)

**Comment by icefalcon2225** [comment]
I saw the Xperia XA2 patch that you suggested to @dimitar10 in related issue #121:
   -  sonyxperiadev/device-sony-pioneer@8e138d8

The point of that patch is to make the property **ro.telephony.default_network** match between the AOSP and factory image.   I wanted to see if something similar would be relevant for the Xperia XZ1.

Although I wasn't able to get fix the delay in the getting SIM connectivity, I did find some things that I thought might be helpful for those that are currently debugging the issue.

On the factory image, where the SIM works well, I see:
```
G8342:/ $ getprop | grep default_network
[ro.telephony.default_network]: [9,0]
```
But on the AOSP 8.1.0_r35 image with the SIM connectivity delay, I see:
```
poplar:/ $ getprop | grep default_network
[ro.telephony.default_network]: [9]
```
I tried to mimic the referenced patch by making a change to device/sony/poplar/aosp_g8342.mk:
```
-    ro.telephony.default_network=9,1
+    ro.telephony.default_network=9,0
```
However, that didn't seem to fix anything --- the default_network property is still "[9]", and the SIM still has the 2.5 minute delay in getting connectivity.

I did a test where I tried to force the default_network to [9,0] by changing device/sony/common/common-prop.mk:
```
-    ro.telephony.default_network=9
+    ro.telephony.default_network=9,0
```
This does change the value of the property that I see on the phone.  However, it doesn't fix the connectivity delay.  It also results in the following dialog every time that Android starts up:
```
Android System

There's an internal problem with your device.  Contact your manufacturer
for details.

OK
```
So, that's obviously not the correct fix.  

Based on what I've described here, is there a different change that you recommend that I try?

Thank you.

**Comment by icefalcon2225** [comment]
@dimitar10 
Here is the radio logcat for my AOSP 8.1.0_r35 build (without the modifications that I tried from the previous post), from boot until the SIM card achieves connectivity.  I've also included the radio logcat for the factory image for comparison.

[aosp_r35_radio_logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2283709/aosp_r35_radio_logcat.txt)
[factory_radio_logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/2283710/factory_radio_logcat.txt)

Let me know if there is any other information that would be helpful to you.

Thanks.

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-poplar/commit/0c242fb505542c3800adcd831be86ba2ee63044b
will fix the ro.telephony.default_network=9 error and now getprop | grep ro.telephony.default_network will return the proper value

**Comment by jerpelea** [comment]
@icefalcon2225 @dimitar10 
We managed to replicate the issue on a XA2 devices and now we are looking for the cause

**Comment by icefalcon2225** [comment]
> sonyxperiadev/device-sony-poplar@0c242fb

I applied this patch, and the default_network property now contains the proper values on the XZ1:
```
poplar:/ $ getprop | grep ro.telephony.default_network
[ro.telephony.default_network]: [9,1]
```
I will apply the solution for dual SIM devices once that is available.  Thank you again for your help.

**Comment by jerpelea** [comment]
The investigation is ongoing 

In the meantime for the dual sim devices that use only 1 sim there is a workaround 
setprop persist.radio.multisim.config none
setprop persist.multisim.config none
reboot

**Comment by icefalcon2225** [comment]
Hi Alin,

We are currently using only one SIM in the devices, so the workaround
should be okay for us for now.  I will test it today.

Thank you for your help!

Mike

**Comment by icefalcon2225** [comment]
We are currently using only one SIM in the devices, so the workaround should be okay for us for now.  I will test it today.

Thank you for your help!

**Comment by icefalcon2225** [comment]
I tested and confirmed that this change disables the second SIM and eliminates the 2.5 minute delay in obtaining cellular connectivity.  I edited the properties directly in **./device/sony/poplar/aosp_g8342.mk** so that the image is created with the change already in place.  This appears to work well.

Thank you again for your help.

**Comment by jerpelea** [comment]
please test the commit
https://github.com/sonyxperiadev/device-sony-common/commit/9d8c552a1758dc50c3ce13a7822bd6e6e9ef2f51

**Comment by jerpelea** [comment]
@icefalcon2225 plase test the fix

**Comment by updateing** [comment]
I have the same problem (maple, Linux 4.4.147, vendor r15) and the fix works for me. Two SIMs registers to network the moment signal icons show up.

**Comment by icefalcon2225** [comment]
I tested this change and confirmed that it fixes the connectivity issue with a dual-SIM Xperia XZ1 G8342. I tested it on using kernel 4.4.132 and Android 8.1.0_r26.  I was able to use either SIM for calls and for data, and experienced minimal delay establishing cellular connectivity with both SIMs.  It appears to be working as well as the factory image.

Thank you for resolving this issue.

**Comment by MartinX3** [comment]
@jerpelea 
Maybe a regression.
Same problem on the XZ2 with AOSP 9.0 and OEM v5 blobs.

Same on the resurrection remix rom.
