### ISSUE TITLE
Camera disconnect

### ISSUE THREAD

**Issue by sjllls** [sonyxperiadev/bug_tracker#293]
**Platform:**  Yoshino
**Device:**  Poplar
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Camera disconnected after waking from the screen-off state

**Comment by sjllls** [comment]
> What's your problem?
> Are you normal?
> You spam all our threads that you have working phone and now open another thread where you post that your phone not working _facepalm_
> [#281 (comment)](https://github.com/sonyxperiadev/bug_tracker/issues/281#issuecomment-449978432)

Why do you say that I am spaming?
The build date is not the same. The codes are changjng.
I am only reporting the latest situation of the source code.
All the Rom I built were upload to AndroidFilesHost.
I am right, you can go to test.
No try, no comment.

**Comment by MartinX3** [comment]
Please be polite, people.
This is a bug tracker, we want to hunt bugs/arachnids. :)

**Comment by russel5** [comment]
Give please a link, what code was changed. Because not changed anything, that may broke or fix camera since oem v4 was released.

**Comment by sjllls** [comment]
> Give please a link, what code was changed. Because not changed anything, that may broke or fix camera since oem v4 was released.

2019.1.5：I built aosp_g8342-ota-eng.sjll-20190105-HMP.zip
 https://androidfilehost.com/?w=files&flid=288159
2018.12.24 , I tested poplar-img-9-PQ1A.181205.006-20181222.zip 
 https://androidfilehost.com/?w=files&flid=286597

**Comment by sjllls** [comment]
> Give please a link, what code was changed. Because not changed anything, that may broke or fix camera since oem v4 was released.

Besides, sleep dead issue had been solved in 2019.1.5 aosp I built on poplar.

**Comment by sjllls** [comment]
> Give please a link, what code was changed. Because not changed anything, that may broke or fix camera since oem v4 was released.

Nothing I changed for source code. Just used offcial source code. Both poplar and maple.
I build and tested AOSP on maple, 2019.1.6.
Maple still have sleep dead problem, once the screen is closed, it can no longer wake up.
But poplar works well.
If you need , I can upload ROM for you to test.
![index](https://user-images.githubusercontent.com/29087038/50734915-5ac9d000-11e1-11e9-93c6-0ed98a45b842.jpeg)

**Comment by sjllls** [comment]
> @sjllls so if i understand correctly, those two builds differ only in the changes committed between 24.12 and 05.01?
> because a quick check reveals that there hasn't been that many commits in that span.
> Actually, i could safely state that there hasn't been any commits concerning yoshino's wakeup issue nor the camera's instability.

Yes, those two builds  differ only in the changes committed between 24.12 and 05.01. I had never modified the source codes.
Sleep dead issue never happen on poplar on 05.01 build. But maple still have it on 06.01 build.

**Comment by oshmoun** [comment]
at this point, this looks random enough to count as luck.
but in any case, it would be great if @russel5 were able to test those builds and confirm/deny the findings of @sjllls 
unfortunately, no yoshino device here to test :sweat_smile:

**Comment by russel5** [comment]
Will not even try, because not change anything.
And deep sleep issue still exist on lilac.
Im not trust this person.

**Comment by sjllls** [comment]
> Will not even try, because not change anything.
> And deep sleep issue still exist on lilac.
> Im not trust this person.

Just watch this video , camera doesn't work on AOSP built on 2019.1.4 for poplar after booting?
Everything I said is true. 
No test, no commit. @russel5
I will let XZ1 sleep for 4 hours to test sleep dead issue. 
https://youtu.be/oxvPGbAMTos

@oshmoun  You are right, nobody has right to deny other people without evidence.

**Comment by jerpelea** [comment]
I tested the device and the camera works fine 
please provide instructions how to trigger the bug

**Comment by jerpelea** [comment]
please be more specific howto replicate the bug

**Comment by jerpelea** [comment]
[  525.322469] hyp_assign_table: Failed to assign memory protection, ret = -22
[  525.322473] ADSPRPC: hyp_assign_phys fail err -1
[  525.323018] map->phys fe000000, map->size 2097152
[  525.323219] scm_call failed: func id 0x42000c16, ret: -2, syscall returns: 0x10000014, 0x0, 0x0

**Comment by sjllls** [comment]
> please be more specific howto replicate the bug

Thanks for you advice, I will try a new build to test camera.
I will be more specific to replicate the bug in future.
