### ISSUE TITLE
[Loire] [Kugo] Errors when activating/deactivating NFC

### ISSUE THREAD

**Issue by chris42** [sonyxperiadev/bug_tracker#438]
**Platform:** Loire
**Device:** Kugo
**Kernel version:** 4.9 (4.9.182-g6593c13-dirty)
**Android version:** 9

**Description**
While checking Issue #437 I found some errors with libnfc_nci in the log while activating NFC and deactivating it. Not sure if the errors below are OK or should be fixed. NFC seems to work, as I could write and read tags. So could be minor.

**How to reproduce**
Turn NFC ON and OFF

```
07-07 11:03:13.150  3404  4708 I NfcService: Enabling NFC
07-07 11:03:13.151   541   596 E RQBalance-PowerHAL-HALEXT: Unexpected argument. Bailing out.
07-07 11:03:13.153   541   596 D RQBalance-PowerHAL-HALEXT: Arguments: 3
07-07 11:03:13.165   541   596 D RQBalance-PowerHAL-HALEXT: Arg[0]: 0x101
07-07 11:03:13.166   541   596 D RQBalance-PowerHAL-HALEXT: Arg[1]: 0x20e
07-07 11:03:13.166   541   596 D RQBalance-PowerHAL-HALEXT: Arg[2]: 0x30e
07-07 11:03:13.169   541   596 D RQBalance-PowerHAL-HALEXT: Arg[3]: 0x0
07-07 11:03:13.181   527  4200 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 124, path = 0, app id = 0x11130, sample rate = 48000
07-07 11:03:13.182   527  4200 D ACDB-LOADER: ACDB -> send_asm_topology
07-07 11:03:13.182   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
07-07 11:03:13.183   527  4200 D ACDB-LOADER: ACDB -> send_adm_topology
07-07 11:03:13.184   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
07-07 11:03:13.184   527  4200 D ACDB-LOADER: ACDB -> send_audtable
07-07 11:03:13.185   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
07-07 11:03:13.186   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
07-07 11:03:13.186   527  4200 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
07-07 11:03:13.187   527  4200 D ACDB-LOADER: ACDB -> send_audvoltable
07-07 11:03:13.187   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
07-07 11:03:13.188   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
07-07 11:03:13.189   527  4200 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
07-07 11:03:13.189   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
07-07 11:03:13.190   527  4200 D ACDB-LOADER: ACDB -> send_audstrmtable
07-07 11:03:13.190   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
07-07 11:03:13.191   527  4200 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 56
07-07 11:03:13.191   527  4200 D ACDB-LOADER: ACDB -> send_afe_topology
07-07 11:03:13.192   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
07-07 11:03:13.193   527  4200 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 124, Topology Id 1025d
07-07 11:03:13.193   527  4200 D ACDB-LOADER: ACDB -> send_afe_cal
07-07 11:03:13.194   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
07-07 11:03:13.194   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
07-07 11:03:13.195   527  4200 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
07-07 11:03:13.195   527  4200 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 124 path = 0
07-07 11:03:13.196   527  4200 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
07-07 11:03:13.197   527  4200 D hardware_info: hw_info_append_hw_type : device_name = speaker
07-07 11:03:13.197   527  4200 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
07-07 11:03:13.198   527  4200 D audio_route: Apply path: speaker
07-07 11:03:13.229  3404  4708 I com.android.nf: ConfigFile - Parsing file '/vendor/etc/libnfc-nci.conf'
07-07 11:03:13.229  3404  4708 I com.android.nf: ConfigFile - [NFC_DEBUG_ENABLED] = 0
07-07 11:03:13.230  3404  4708 I com.android.nf: ConfigFile - [NFA_STORAGE] = "/data/vendor/nfc"
07-07 11:03:13.230  3404  4708 I com.android.nf: ConfigFile - [UICC_LISTEN_TECH_MASK] = 0x07
07-07 11:03:13.231  3404  4708 I com.android.nf: ConfigFile - [AID_FOR_EMPTY_SELECT] = {08:A0:00:00:01:51:00:00:00}
07-07 11:03:13.231  3404  4708 I com.android.nf: ConfigFile - [SCREEN_OFF_POWER_STATE] = 1
07-07 11:03:13.231  3404  4708 I com.android.nf: ConfigFile - [POLLING_TECH_MASK] = 0xEF
07-07 11:03:13.232  3404  4708 I com.android.nf: ConfigFile - [NFA_MAX_EE_SUPPORTED] = 0x02
07-07 11:03:13.232  3404  4708 I com.android.nf: ConfigFile - [AID_MATCHING_MODE] = 0x01
07-07 11:03:13.233  3404  4708 I libnfc_nci: [INFO:NfcAdaptation.cc(460)] NfcAdaptation::InitializeHalDeviceContext: INfc::getService()
07-07 11:03:13.237  3404  4708 I libnfc_nci: [INFO:NfcAdaptation.cc(466)] NfcAdaptation::InitializeHalDeviceContext: INfc::getService() returned 0x752241c6c0 (remote)
07-07 11:03:13.238   527  4200 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
07-07 11:03:13.238   527  4200 D audio_route: Apply path: low-latency-playback
07-07 11:03:13.246  3404  4711 E libnfc_nci: [ERROR:gki_ulinux.cc(98)] gki_task task_id=0 terminating
07-07 11:03:13.257   540   540 D EseAdaptation: EseAdaptation::InitializeHalDeviceContext: Failed to retrieve the NXP ESE HAL!
07-07 11:03:13.300   540  4718 D NxpHal  : getChipType HwVersion : 0x01
07-07 11:03:13.300   540  4718 D NxpHal  : getChipType Product : PN547C2
07-07 11:03:13.306   540   540 E NxpFwDnld: free library SUCCESS !!
07-07 11:03:13.308   540   540 E NxpFwDnld: FW Image Length - ImageInfoLen 34590
07-07 11:03:13.308   540   540 E NxpFwDnld: FW Image Info Pointer - pImageInfo 0x712a8df430
07-07 11:03:13.308   540   540 E NxpFwDnld: FW Major Version Num - 1
07-07 11:03:13.309   540   540 E NxpFwDnld: FW Minor Version Num - 26
07-07 11:03:13.310   540   540 E NxpFwDnld: FW Image Length - 34590
07-07 11:03:13.313   527  4200 E msm8916_platform: ramp_speaker_gain: Could not get ctl for mixer cmd - Left Speaker Gain or Right Speaker Gain, not applying speaker gain ramp
07-07 11:03:13.314   527  4200 D audio_hw_primary: out_write: retry previous failed cal level set
07-07 11:03:13.314   540   540 E NxpFwDnld: FW Image Info Pointer - 0x712a8df430
07-07 11:03:13.315   540   540 E NxpHal  : FW version for FW file = 0x126
07-07 11:03:13.315   540   540 E NxpHal  : FW version from device = 0x80127
07-07 11:03:13.316   540   540 E NxpHal  : FW download denied while SPI in use, Continue NFC init
07-07 11:03:13.462  3404  4712 E libnfc_nci: [ERROR:nfa_ee_act.cc(1980)] nfa_ee_nci_mode_set_rsp p_rsp->status:0x00
07-07 11:03:13.512  3404  4712 E libnfc_nci: [ERROR:HciEventManager.cpp(151)] Incorrect Pipe Id
07-07 11:03:13.525  3404  4708 D NfcService: NCI_Version: 16
07-07 11:03:13.526  3404  4708 D NdefPushServer: start, thread = null
07-07 11:03:13.527  3404  4708 D NdefPushServer: starting new server thread
07-07 11:03:13.530  3404  4721 D NdefPushServer: about create LLCP service socket
07-07 11:03:13.532  3404  4721 D NdefPushServer: created LLCP service socket
07-07 11:03:13.533  3404  4721 D NdefPushServer: about to accept
07-07 11:03:13.542  3404  4708 W SoundPool: Use of stream types is deprecated for operations other than volume control
07-07 11:03:13.542  3404  4708 W SoundPool: See the documentation of SoundPool() for what to use instead with android.media.AudioAttributes to qualify your playback use case
07-07 11:03:13.578  3404  4726 I OMXClient: IOmx service obtained
07-07 11:03:13.580   676  3248 I OMXMaster: makeComponentInstance(OMX.google.vorbis.decoder) in omx@1.0-service process
07-07 11:03:13.589   676  3248 E OMXNodeInstance: getConfig(0xf16a98a0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
07-07 11:03:13.595   526   526 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0x7e4d22c100, 32768)
07-07 11:03:13.633   526   526 I chatty  : uid=1000(system) allocator@1.0-s identical 10 lines
07-07 11:03:13.634   526   526 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0x7e4d22c100, 32768)
07-07 11:03:13.751  3404  4729 I OMXClient: IOmx service obtained
07-07 11:03:13.753   676  3248 I OMXMaster: makeComponentInstance(OMX.google.vorbis.decoder) in omx@1.0-service process
07-07 11:03:13.758   676  3248 E OMXNodeInstance: getConfig(0xf16a98a0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
07-07 11:03:13.765   526   526 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0x7e4d22c100, 32768)
07-07 11:03:13.805   526   526 I chatty  : uid=1000(system) allocator@1.0-s identical 10 lines
07-07 11:03:13.807   526   526 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0x7e4d22c100, 32768)
07-07 11:03:13.943  3404  4732 I OMXClient: IOmx service obtained
07-07 11:03:13.945   676   719 I OMXMaster: makeComponentInstance(OMX.google.vorbis.decoder) in omx@1.0-service process
07-07 11:03:13.952   676   719 E OMXNodeInstance: getConfig(0xf16a98a0:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
07-07 11:03:13.957   526   526 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0x7e4d22c100, 32768)
07-07 11:03:15.518   671   785 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
07-07 11:03:13.996   526   526 I chatty  : uid=1000(system) allocator@1.0-s identical 10 lines
07-07 11:03:13.998   526   526 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0x7e4d22c100, 32768)
07-07 11:03:16.538   527   931 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback
07-07 11:03:16.541   527   931 D hardware_info: hw_info_append_hw_type : device_name = speaker
07-07 11:03:16.541   527   931 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
07-07 11:03:18.992   990   990 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
07-07 11:03:21.373  3404  4737 I NfcService: Disabling NFC
07-07 11:03:21.385   541   596 E RQBalance-PowerHAL-HALEXT: Unexpected argument. Bailing out.
07-07 11:03:21.387   541   596 D RQBalance-PowerHAL-HALEXT: Arguments: 3
07-07 11:03:21.387   541   596 D RQBalance-PowerHAL-HALEXT: Arg[0]: 0x101
07-07 11:03:21.388   541   596 D RQBalance-PowerHAL-HALEXT: Arg[1]: 0x20e
07-07 11:03:21.389   541   596 D RQBalance-PowerHAL-HALEXT: Arg[2]: 0x30e
07-07 11:03:21.392   541   596 D RQBalance-PowerHAL-HALEXT: Arg[3]: 0x0
07-07 11:03:21.394   527  4200 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 124, path = 0, app id = 0x11130, sample rate = 48000
07-07 11:03:21.394   527  4200 D ACDB-LOADER: ACDB -> send_asm_topology
07-07 11:03:21.394  3404  4737 D NfcService: clear T3t Identifiers Cache
07-07 11:03:21.395   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
07-07 11:03:21.396   527  4200 D ACDB-LOADER: ACDB -> send_adm_topology
07-07 11:03:21.397   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
07-07 11:03:21.398   527  4200 D ACDB-LOADER: ACDB -> send_audtable
07-07 11:03:21.398   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
07-07 11:03:21.399   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
07-07 11:03:21.400   527  4200 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
07-07 11:03:21.400   527  4200 D ACDB-LOADER: ACDB -> send_audvoltable
07-07 11:03:21.401   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
07-07 11:03:21.401   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
07-07 11:03:21.402   527  4200 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
07-07 11:03:21.402   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
07-07 11:03:21.403  3404  4737 D NfcP2pLinkManager: enableDisable: llcp deactivate
07-07 11:03:21.403   527  4200 D ACDB-LOADER: ACDB -> send_audstrmtable
07-07 11:03:21.404  3404  4737 I NfcP2pLinkManager: LLCP deactivated.
07-07 11:03:21.404   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
07-07 11:03:21.405  3404  4737 I NfcP2pLinkManager: Duplicate onLlcpDectivated()
07-07 11:03:21.405   527  4200 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 56
07-07 11:03:21.406   527  4200 D ACDB-LOADER: ACDB -> send_afe_topology
07-07 11:03:21.407   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
07-07 11:03:21.407   527  4200 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 124, Topology Id 1025d
07-07 11:03:21.408   527  4200 D ACDB-LOADER: ACDB -> send_afe_cal
07-07 11:03:21.409   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
07-07 11:03:21.409   527  4200 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
07-07 11:03:21.410   527  4200 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
07-07 11:03:21.410   527  4200 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 124 path = 0
07-07 11:03:21.411   527  4200 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
07-07 11:03:21.411   527  4200 D hardware_info: hw_info_append_hw_type : device_name = speaker
07-07 11:03:21.412   527  4200 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
07-07 11:03:21.413   527  4200 D audio_route: Apply path: speaker
07-07 11:03:21.424  3404  4720 E libnfc_nci: [ERROR:NativeLlcpServiceSocket.cpp(66)] nativeLlcpServiceSocket_doAccept: fail accept
07-07 11:03:21.458   527  4200 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
07-07 11:03:21.459   527  4200 D audio_route: Apply path: low-latency-playback
07-07 11:03:21.467  3404  4737 D NdefPushServer: stop, thread = Thread[Thread-12,5,main]
07-07 11:03:21.467  3404  4737 D NdefPushServer: shuting down server thread
07-07 11:03:21.485  3404  4721 E libnfc_nci: [ERROR:NativeLlcpServiceSocket.cpp(66)] nativeLlcpServiceSocket_doAccept: fail accept
07-07 11:03:21.486  3404  4721 D NdefPushServer: IO error
07-07 11:03:21.499  3404  4722 E libnfc_nci: [ERROR:NativeLlcpServiceSocket.cpp(66)] nativeLlcpServiceSocket_doAccept: fail accept
07-07 11:03:21.518  3404  4712 E libnfc_nci: [ERROR:HciEventManager.cpp(151)] Incorrect Pipe Id
07-07 11:03:21.531   540  4718 E NxpHal  : Ignoring read, HAL close triggered
07-07 11:03:21.536   527  4200 E msm8916_platform: ramp_speaker_gain: Could not get ctl for mixer cmd - Left Speaker Gain or Right Speaker Gain, not applying speaker gain ramp
07-07 11:03:21.537   527  4200 D audio_hw_primary: out_write: retry previous failed cal level set
07-07 11:03:22.468  3404  4712 E libnfc_nci: [ERROR:gki_ulinux.cc(666)] GKI TASK_DEAD received. exit thread 3...
07-07 11:03:22.469  3404  4712 E libnfc_nci: [ERROR:gki_ulinux.cc(98)] gki_task task_id=3 terminating
07-07 11:03:22.569  3404  4710 E libnfc_nci: [ERROR:gki_ulinux.cc(98)] gki_task task_id=4 terminating
07-07 11:03:23.169  2884  2884 V NavigationBar: onRotationProposal proposedRotation=ROTATION_90, winRotation=ROTATION_0, isValid=true, mNavBarWindowState=WINDOW_STATE_SHOWING, rotateSuggestionsDisabled=false, isRotateButtonVisible=false
```

**Comment by ix5** [comment]
Syncing up `p-mr1` of device-sony-loire to `master` should resolve this. For now, you can cherry-pick the `move-nfc-nci` commit.

**Comment by chris42** [comment]
Hmmm... I have that commit already in my sources and compile. Just manually checked the files for the changes.

**Comment by jerpelea** [comment]
please sync the code 
I can not replicate the bug

**Comment by chris42** [comment]
My phone is running a build from beginning of October. Mentioned changes should be included then already? Errors still appear in the log.
Haven't build since then, as it was EOL of Android 9 and the Issues with Wifi, Crashes, etc. haven't had progress.
I also have a recent Android 10 build with Kernel 4.9, which is showing similar/same error (see [log.txt](https://github.com/sonyxperiadev/bug_tracker/files/4054482/log.txt)).

I can do another build, but it will take some time. Let me know if you need it.

**Comment by MarijnS95** [comment]
Just to clear up some confusion this thread: _nothing is broken_. Or at least that's what the issue suggests:

> Not sure if the errors below are OK or should be fixed. NFC seems to work

Looking at the errors this might be a simple case of timing and/or badly coded thread/socket handling. All the relevant code is open-source (`hardware/nxp/nfc` and `packages/apps/Nfc`).

Feel free to debug if you have the time, but nothing seems fatal nor worrisome.

**Comment by chris42** [comment]
Don't think there is confusion, I myself wrote, that NFC works (at least I can read NFC tags).
However the error in the log still persists. I am not a developer, hence I cannot debug it, nor tell, if this is critical. But I am always in favor of reporting such things and have a say by the experts.

My answer to @jerpelea was mainly to notice, that the fix that @ix5 mentioned is at least not solving the error log (might fix something else, but I don't know) and recent sources seem to still have it.

**Comment by MarijnS95** [comment]
> Don't think there is confusion

It seems like @jerpelea was looking for an actual broken feature ("I can not replicate the **bug**"), which is solely what I intended to clear up.

> But I am always in favor of reporting such things and have a say by the experts.

Have fun reporting thousands of things; there are many more "error" messages that unfortunately have no relevance at all. Not to mention debug information logged on the error level.

If something is actually broken, sluggish, spams the logs or screams overvolt/fire, by all means report it. For all other error messages: please be skeptical. As you must have undoubtedly seen we are heavily "understaffed" (however that works for open-source projects with free-time contributors) and have no time to go through every little message that pops up.
It is obviously a massive grey area since only few can identify whether something is critical or dangerous, the same people who don't have enough time to scrutinize the logs on every platform and device.
