### ISSUE TITLE
[Q][ganges] Recovery breaks booting into system.

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#471]
**Description**
The issue is that even after adding the patch that fixes the recovery on ganges its still not displaying anything on ganges and it doesnt show anything. Which is because of the kernel panic i suppose.
But when you want to reboot into system it wont let you.
It will boot straight back into recovery.
Only way to fix that is to clean the misc partition. Which isnt possible on stock recovery due to ownership.
So basically you have to boot TWRP which wont load either and will show black screen and clean the partition from that. After that i can again boot into android.

**How to reproduce**
Boot into recovery on ganges on Q.

**Additional context**
[dmesg10.txt](https://github.com/sonyxperiadev/bug_tracker/files/3662713/dmesg10.txt)
For anybody without bootable phone now the fix is for now to boot TWRP image. But fastboot boot wont work if you put device into fastboot via hardware buttons. You have to use adb reboot bootloader then boot the TWPR image. (Otherwise it would ignore the TWRP image and boot the old one). Then do `adb shell dd if=/dev/zero of=/dev/block/bootdevice/by-name/misc` from terminal.

**Comment by Haxk20** [comment]
And yes i have bricked phone now because of that stupid bootloader bug where you cant flash anything over fastboot without USB hub. <----- That one really sucks.

**Comment by Haxk20** [comment]
And i cannot provide anything more. Well i can post here the boot image. I fixed the phone with friend USB hub (Waiting for mine to arrive :( ) and i cannot risk being without phone this weekend.

**Comment by Haxk20** [comment]
[boot-debug.zip](https://github.com/sonyxperiadev/bug_tracker/files/3662776/boot-debug.zip)

**Comment by MarijnS95** [comment]
> Only way to fix that is to clean the misc partition. Which isnt possible on stock recovery due to ownership.

Are you sure? AOSP recovery should have root access (might require `adb root`, I can't remember)

As for TWRP, I remember you saying you use [my patches](https://github.com/MarijnS95/device-sony-ganges/commits/android-9.0) for TWRP, and it still doesn't work?
I don't see a panic in the dmesg, only a warning.

Any particular reason why the phone isn't booting in the first place? `cat /dev/block/bootdevice/by-name/misc`? It could be ~RescueParty~ [PartyCrasher](https://github.com/MarijnS95/device-sony-common/commit/6972f73107a4ca99df091666f300938a103bdda4). Though all vital services should be running now.

**Comment by Haxk20** [comment]
@MarijnS95 Well i havent tried adb root. Not in the mood exactly to try it now with the chance that phone will be bricked for the weekend. 

As i said. I use your patches for TWRP. That works just fine but for some reason if i try to boot TWRP with 10 installed it would still show just black screen as in AOSP recovery.
By your patch i mean the one that fixes AOSP recovery.

Sadly i wish i could try cating the partition but as i said im not risking bricking the phone again until USB hub arrives.

But what i know that was weird is that if i adb shell into the bricked phone is that i get a shell but it does not show mermaid. Its basically just $:.

**Comment by MarijnS95** [comment]
> But what i know that was weird is that if i adb shell into the bricked phone is that i get a shell but it does not show mermaid. Its basically just $:.

It's a simplified process that probably doesn't have `PS1` set or doesn't care. No biggie.

I'll try to run AOSP recovery later today, and see what's going on with the patch and `adb root`.

Anyway, what exactly is currently bricking your phone? Seeing the title, is there something happening with recovery that causes it to not boot into system anymore? What are you running over the weekend to not brick the device; Android 10?

**Comment by Haxk20** [comment]
@MarijnS95 And indeed it is very much possible that rebooting the device to recovery is as your awesome named commit said PartyCrasher (I must say i love that commit name. Good sense of humor).
BTW i unpacked that boot image to see the recovery ramdisk. And it does not contain su file.

To answer that comment you just posted.
As i said just above i dont see su file in the ramdisk so adb root cant work.

Bricking the device is that it wont boot to system because it will boot to recovery.
It is as you said probably because of RescueParty.

And the reason why i cant brick the device is that i dont have USB hub at home (Yes i know weird to hear from tech person) but my old 30$ one broke for no reason and i would have to wait until monday morning to get access to USB hub to boot TWRP. Which is just not acceptable as i have some very important life stuff on weekend and i need phone working. If i had USB hub with me it wont be an issue to test it but i dont and as i said i need the device.
Yes i run Android 10 at this point. And i think that maybe the 4.9 kernel may have something to do with why its not showing anything in the recovery. Well scratch that. When booting TWRP image it has android 9 kernel and ramdisk so TWRP should show up but it does not.

I know its a weird issue but im sure you agree that recovery is needed part of AOSP. And having it broken to the stage that it will cause device not boot into system is unaccaptable.

**Comment by Haxk20** [comment]
@MarijnS95 And while yes i looked wrong at the dmesg. Its warning only but still it contains loooooot of errors. It cant find ueventd or almost all the stuff it needs. That should not happen.

**Comment by MarijnS95** [comment]
@Haxk20 no worries, `adb root` doesn't need `su`.
It starts as `root` and drops permissions if `service.adb.root` is not `1` explicitly.
https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r3/adb/daemon/main.cpp#95
Assuming you build `userdebug`, `ro.debuggable` should be `1`/`true`.

**Comment by Haxk20** [comment]
@MarijnS95 Woah. I didnt know about that adb root thing. Thanks.
Obviusly i build userdebug.

Yes that must be the reason why you havent noticed the issue.
TBH its really anoying.
Try without the keyboard hub and see if you can flash the device.

Yeah i hope 4.14 will fix few issues TBH. Like the 30 second sleep wifi disconnect issue.
BTW i noticed Android 10 build guide on sony website. It says about 4.14. I dont think thats a good thing as its not even ready for daily use as far as i know and android 10 building has lot of issues. If you could speak to other people to remove that or we will get lot of people reporting build fail bugs.

**Comment by MarijnS95** [comment]
"Unfortunately" I can only tell you my device works absolutely fine on any USB port on the system and laptop. Even tried flipping the Type-C to see if the controller is a bit crazy, but it makes no difference.

Just to be sure, you said _flashing_. I didn't test `fastboot boot` though that shouldn't make any difference.

I fully agree on the 4.14 part, and have been asking about adding at least a warning.
Android 10 not so much since that's almost rock-solid and we _really_ need some community testers daily-driving it to iron out the last kinks. But that is totally held back and masked by 4.14.

**Comment by Haxk20** [comment]
@MarijnS95 I will test the recovery with 4.14 when i get USB hub.

Thanks for trying the USB hub issue. I read about the USB hub first in issue on this repo.
[The issue](https://github.com/sonyxperiadev/bug_tracker/issues/305)
If we could get the devs that manage the bootloader to look at it im sure they could figure out whats wrong. Heck i would be glad to do a test bunny for them just for this to get fixed.

**Comment by MartinX3** [comment]
@Haxk20
I had an experience in a similar direction.
But I think that it was caused at my side by a not always perfect voltage stability on my thinkpad USB slots in Linux.
Or the windows platform tools are just more robust

While charging at the computer I had touch screen ghost touches, too.

A usb hub may flat the voltage spikes.

**Comment by Haxk20** [comment]
I used USB doctor and i can tell you that the voltage is 4.96V perfect. No spikes when USB connected. So i dont see where could be the issue. Anyway the main issue here is the recovery and not fastboot so lets keep it recovery issue. Maybe i will open new issue for the fastboot thing later today so we can find out the real cause of it.

**Comment by Haxk20** [comment]
Seems like [this commit](https://github.com/sonyxperiadev/device-sony-common/commit/566bf9a498ca3b2b628d5ff07202550cdac604d7) could fix the issue. Will test once i get USB hub. (No it still havent arrived :()

**Comment by sraase** [comment]
Try to use a different cable and/or try to reverse the connector on the phone side. Some phones may react weird when the USB-C connector is plugged in backwards (in which case normal USB continues to work).

**Comment by Haxk20** [comment]
@sraase I tried. Doesnt work. If i use USB hub i can connect the cable however i want. Works just fine. It seems that sony bootloader has some issues with laptop USB ports and it started happening even on PC which i luckily dont use anymore.

**Comment by Haxk20** [comment]
Closing as this is no longer the case for a while now. But still broken recovery.
