### ISSUE TITLE
[Yoshino][Lilac][Android-10] Slow screen response and then black

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#534]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.167-ga1f504564625
**Kernel compiler:** clang and gcc (logs are from clang kernel)
**Android version:** android-10.0.0_r21
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v3_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ1A.200105.002 eng.stefan.20200203.223639

**Description**
Phone boots, after entering SIM-PIN which is very slow, it then requests device PIN after that has been entered as well screen goes off after some time due to inactivity resp. in-responsiveness or slowness of login. No way to reactivate the screen, it remains blank.

The commit from the kernel-version can't be found, sine it is commit sonyxperiadev/kernel@87e8743ca934ea14607c2060f3fa6fc186443e7d + sonyxperiadev/kernel#2177 see as well my git log:
``` 
a1f5045646250adf44449f56dc34509ea6b46fb1 [...] Revert "lib/genalloc.c: use vzalloc_node() to allocate the bitmap"
87e8743ca934ea14607c2060f3fa6fc186443e7d [...] arm64: configs: somc: update auto-generated defconfig for all platforms
```

**Symptoms**
- Touch and Screen very in-responsive
- After login, screen goes off and does not come back

**How to reproduce**
- Build current version as I have done with e.g.: https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh
- Flash all images, that is in my case:
```
stefan@mars:~/android/bin/current-4.14$ ls -la
insgesamt 28
drwxr-xr-x 1 stefan stefan 136 Feb  4 21:43 .
drwxr-xr-x 1 stefan stefan 544 Feb  4 21:42 ..
lrwxrwxrwx 1 stefan stefan  33 Feb  4 21:43 boot.img -> ../2020.02.03-4.14/boot-clang.img
lrwxrwxrwx 1 stefan stefan  28 Feb  4 21:43 cache.img -> ../2020.02.03-4.14/cache.img
lrwxrwxrwx 1 stefan stefan  60 Feb  1 16:47 oem.img -> ../SW_binaries_for_Xperia_Android_10.0.7.1_r1_v3_yoshino.img
lrwxrwxrwx 1 stefan stefan  31 Feb  4 21:43 recovery.img -> ../2020.02.03-4.14/recovery.img
lrwxrwxrwx 1 stefan stefan  29 Feb  4 21:43 system.img -> ../2020.02.03-4.14/system.img
lrwxrwxrwx 1 stefan stefan  31 Feb  4 21:43 userdata.img -> ../2020.02.03-4.14/userdata.img
lrwxrwxrwx 1 stefan stefan  29 Feb  4 21:43 vendor.img -> ../2020.02.03-4.14/vendor.img
```
- Boot to the phone and try use it

**Additional context**
Captured logcat and dmesg:
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4156139/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4156142/logcat.log)

**Comment by AlbertBackenhof** [comment]
I'm experiencing this as well and did some digging. In logcat for Android 10 I get "Faking VSYNC due to driver stall" every 1 sec, which is also about the same fps my screen shows (estimated by me).

I built and flashed the latest Android 9, which haven't got this issue. It doesn't show "Timed out waiting for hw vsync; faking it", which is the previous version of the log-message used above.

To finally make sure the low fps was because of the "Faking VSYNC..." I modified the SurfaceFlinger/Scheduler/EventThread.cpp to timeout after 100ms (instead of 1000ms) when the driver stalls. This resulted in the device screen updating at 10 fps.

I'm guessing this means the graphics driver isn't working properly?

**Comment by yuezhengbaizhi** [comment]
this issue is also happening on poplar, 10 4.14 kernel, the screen is blank after you lock the display and wakes it up

**Comment by stblr** [comment]
I made a new build today and this bug doesn't occur anymore!

**Comment by stefanhh0** [comment]
Good to hear that :-) I currently can't switch to k4.14. Anyway closing this one since it is fixed.

@stblr is audio working fine on lilac? I'll just ask because of: https://github.com/sonyxperiadev/bug_tracker/issues/556

**Comment by stblr** [comment]
@stefanhh0 no it doesn't. #556 can be fixed by enabling CPU frequency scaling in the defconfig though (I will make a pull request tomorrow).

**Comment by stefanhh0** [comment]
I wouldn't have expected that enabling CPU frequency scaling also lets re-appear the snd devices in `/dev/snd` accordingly?! But if it helps go ahead :-) :+1:

**Comment by stblr** [comment]
It only makes the volume buttons responsive again, the audio subsystem is still broken.
