### ISSUE TITLE
Unbootable  XQ- DQ54 with android-13.0.0_r75 and SW_binaries_for_Xperia_Android_13_5.15_v3a_yodo.img

### ISSUE THREAD

**Issue by gecko19** [sonyxperiadev/bug_tracker#840]
**Platform:** : Android 13
**Device:**  : XQ- DQ54
**Kernel version:** 
**Android version:** Android 13
**Software binaries version:** 

**Previously working on**
Has this always been a problem, or is it a new issue?
New issue

**Description**
 I am trying to build the Andoid 13, branch android-13.0.0_r75. However, the SW Binary I am using - SW_binaries_for_Xperia_Android_13_5.15_v3a_yodo.img leaves the phone unbootable. 

Is there a working version of SW Binary+ Android tag which I can use to create a working AOSP build for Yodo/XQ- DQ54?
Also is there a good SW Binary+ Android tag which will work with a high end Sony phone.

**Comment by gecko19** [comment]
Thanks Alin.

**Comment by jerpelea** [comment]
@gecko19 
the bootloop is caused by missing 
https://github.com/sonyxperiadev/device-sony-common/pull/918

Please wait until the PR is merged then the issue should be fixed

Thanks for your patience!
Alin

**Comment by gecko19** [comment]
Thanks @jerpelea . Would there be a commit I can cherry-pick to verify that it is fixed.

Cheers,
George.

**Comment by MarijnS95** [comment]
@gecko19 it's merged, so resyncing the whole tree or just `device/sony/common` (and `device/sony/sepolicy`) on your U or T tree should do the trick.

**Comment by jerpelea** [comment]
it is already merged so 
rm -r out
repo_update 
and build

**Comment by gecko19** [comment]
Hi @jerpelea .  Thanks for this. I did progress a bit further, though the phone still does not boot. I say that it does progress because the sony splash screen now switches off. Please be aware that the phone runs Android 14 from the Emma tool and in reality trying to flash Android 13 AOSP might be a downgrade.

I did the following steps in fastboot mode:
```

fastboot flash oem SW_binaries_for_Xperia_Android_13_5.15_v3a_yodo.img
fastboot flash boot out/target/product/pdx234/boot.img
fastboot flash vbmeta out/target/product/pdx234/vbmeta.img
fastboot flash dtbo out/target/product/pdx234/dtbo.img
fastboot flash recovery out/target/product/pdx234/recovery.img
fastboot flash system out/target/product/pdx234/system.img
fastboot flash vendor out/target/product/pdx234/vendor.img
fastboot flash userdata out/target/product/pdx234/userdata.img
fastboot flash product out/target/product/pdx234/product.img
fastboot flash vbmeta_system out/target/product/pdx234/vbmeta_system.img
fastboot flash system_ext out/target/product/pdx234/system_ext.img
fastboot flash vendor_boot out/target/product/pdx234/vendor_boot.img
fastboot flash vendor_dlkm_a out/target/product/pdx234/vendor_dlkm.img

Sending 'boot_a' (98304 KB)                        OKAY [  2.370s]
Writing 'boot_a'                                   OKAY [  0.064s]
Finished. Total time: 2.458s
Sending 'vbmeta' (8 KB)                            OKAY [  0.006s]
Writing 'vbmeta'                                   OKAY [  0.004s]
Finished. Total time: 0.024s
Sending 'dtbo' (24576 KB)                          OKAY [  0.599s]
Writing 'dtbo'                                     OKAY [  0.016s]
Finished. Total time: 0.628s
Sending 'recovery' (102400 KB)                     OKAY [  2.473s]
Writing 'recovery'                                 OKAY [  0.055s]
Finished. Total time: 2.542s
Sending sparse 'system' 1/2 (720896 KB)            OKAY [ 17.238s]
Writing 'system'                                   FAILED (remote: 'No such partition.')
fastboot: error: Command failed
Sending 'vendor' (200640 KB)                       OKAY [  4.794s]
Writing 'vendor'                                   FAILED (remote: 'No such partition.')
fastboot: error: Command failed
Sending 'userdata' (10200 KB)                      OKAY [  0.249s]
Writing 'userdata'                                 OKAY [ 10.463s]
Finished. Total time: 10.763s
Sending 'product' (282284 KB)                      OKAY [  6.719s]
Writing 'product'                                  FAILED (remote: 'No such partition.')
fastboot: error: Command failed
Sending 'vbmeta_system' (4 KB)                     OKAY [  0.004s]
Writing 'vbmeta_system'                            OKAY [  0.004s]
Finished. Total time: 0.023s
Sending 'system_ext' (468336 KB)                   OKAY [ 11.173s]
Writing 'system_ext'                               FAILED (remote: 'No such partition.')
fastboot: error: Command failed
Sending 'vendor_boot' (98304 KB)                   OKAY [  2.408s]
Writing 'vendor_boot'                              OKAY [  0.053s]
Finished. Total time: 2.476s
fastboot: error: cannot load 'out/target/product/pdx234/vendor_dlkm.img': No such file or directory
gkottack@sunburst-realm:/mnt/AOSP_Sources/SonyXperia1V_A13$
gkottack@sunburst-realm:/mnt/AOSP_Sources/SonyXperia1V_A13$
gkottack@sunburst-realm:/mnt/AOSP_Sources/SonyXperia1V_A13$
gkottack@sunburst-realm:/mnt/AOSP_Sources/SonyXperia1V_A13$ fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.201s
```

Cheers,
George.

**Comment by jerpelea** [comment]
Hi,
please flash Android 13 from Emma then flash Android 13 AOSP

Best regards
Alin

**Comment by jerpelea** [comment]
another note 

all supported devices MUST be flashed from fastbootd 

from fastboot (blue light)
fastboot reboot fastboot  (missing from your flash list)

you will have on the phone a fastbotd menu (like recovery
flash partitions from PC

Best regards
Alin

**Comment by gecko19** [comment]
Hello @jerpelea 

Thanks for getting back to me. I used EMMA to install the Android 13 image on the phone, which it did successfully.

After that I did reboot into fastbootd and flash the OEM partition and the other images from the AOSP sources. Except the vendor_dlkm.img all other images were flashed correctly. After the Sony splash screen, I see the android screen which then switches off. Also, when plugged in, I see a question mark on the battery.  Any ideas why this could be the case.

Thanks a lot for helping me out on this.
Cheers,
G.

```

gkottack@sunburst-realm:/mnt/AOSP_Sources/sony_sw_images$ fastboot reboot fastboot
Rebooting into fastboot                            OKAY [  0.003s]
< waiting for any device >
^C
gkottack@sunburst-realm:/mnt/AOSP_Sources/sony_sw_images$ ^C
gkottack@sunburst-realm:/mnt/AOSP_Sources/sony_sw_images$ ^C
gkottack@sunburst-realm:/mnt/AOSP_Sources/sony_sw_images$ sudo chmod o+w /dev/bus/usb/001/*
gkottack@sunburst-realm:/mnt/AOSP_Sources/sony_sw_images$ fastboot flash oem  SW_binaries_for_Xperia_Android_13_5.15_v3a_yodo.img
Sending sparse 'oem_a' 1/4 (261828 KB)             OKAY [  6.380s]
Writing 'oem_a'                                    OKAY [  0.218s]
Sending sparse 'oem_a' 2/4 (254644 KB)             OKAY [  6.193s]
Writing 'oem_a'                                    OKAY [  0.166s]
Sending sparse 'oem_a' 3/4 (258004 KB)             OKAY [  6.267s]
Writing 'oem_a'                                    OKAY [  0.174s]
Sending sparse 'oem_a' 4/4 (160468 KB)             OKAY [  3.900s]
Writing 'oem_a'                                    OKAY [  0.504s]
Finished. Total time: 23.810s
gkottack@sunburst-realm:/mnt/AOSP_Sources/sony_sw_images$ cd ..
gkottack@sunburst-realm:/mnt/AOSP_Sources$ cd SonyXperia1V_A13/
gkottack@sunburst-realm:/mnt/AOSP_Sources/SonyXperia1V_A13$ ls
Android.bp  WORKSPACE  bionic    bootstrap.bash  cts     developers   device    frameworks  kernel   libnativehelper  packages  platform_testing  repo_update.sh  system  toolchain  vendor
BUILD       art        bootable  build           dalvik  development  external  hardware    libcore  out              pdk       prebuilts         sdk             test    tools
gkottack@sunburst-realm:/mnt/AOSP_Sources/SonyXperia1V_A13$

fastboot flash boot out/target/product/pdx234/boot.img
fastboot flash vbmeta out/target/product/pdx234/vbmeta.img
fastboot flash dtbo out/target/product/pdx234/dtbo.img
fastboot flash recovery out/target/product/pdx234/recovery.img
fastboot flash system out/target/product/pdx234/system.img
fastboot flash vendor out/target/product/pdx234/vendor.img
fastboot flash userdata out/target/product/pdx234/userdata.img
fastboot flash product out/target/product/pdx234/product.img
fastboot flash vbmeta_system out/target/product/pdx234/vbmeta_system.img
fastboot flash system_ext out/target/product/pdx234/system_ext.img
fastboot flash vendor_boot out/target/product/pdx234/vendor_boot.img
fastboot flash vendor_dlkm_a out/target/product/pdx234/vendor_dlkm.img

Sending 'boot_a' (98304 KB)                        OKAY [  2.386s]
Writing 'boot_a'                                   OKAY [  0.125s]
Finished. Total time: 2.515s
Sending 'vbmeta_a' (8 KB)                          OKAY [  0.001s]
Writing 'vbmeta_a'                                 OKAY [  0.003s]
Finished. Total time: 0.007s
Sending 'dtbo_a' (24576 KB)                        OKAY [  0.597s]
Writing 'dtbo_a'                                   OKAY [  0.073s]
Finished. Total time: 0.673s
Sending 'recovery_a' (102400 KB)                   OKAY [  2.484s]
Writing 'recovery_a'                               OKAY [  0.122s]
Finished. Total time: 2.608s
Resizing 'system_a'                                OKAY [  0.002s]
Sending sparse 'system_a' 1/4 (262140 KB)          OKAY [  6.363s]
Writing 'system_a'                                 OKAY [  0.214s]
Sending sparse 'system_a' 2/4 (262140 KB)          OKAY [  6.373s]
Writing 'system_a'                                 OKAY [  0.203s]
Sending sparse 'system_a' 3/4 (262140 KB)          OKAY [  6.375s]
Writing 'system_a'                                 OKAY [  0.185s]
Sending sparse 'system_a' 4/4 (118688 KB)          OKAY [  2.885s]
Writing 'system_a'                                 OKAY [  0.127s]
Finished. Total time: 22.732s
Resizing 'vendor_a'                                OKAY [  0.002s]
Sending 'vendor_a' (200640 KB)                     OKAY [  4.870s]
Writing 'vendor_a'                                 OKAY [  0.179s]
Finished. Total time: 5.056s
Sending 'userdata' (10200 KB)                      OKAY [  0.249s]
Writing 'userdata'                                 OKAY [  0.218s]
Finished. Total time: 0.473s
Resizing 'product_a'                               OKAY [  0.002s]
Sending sparse 'product_a' 1/2 (262140 KB)         OKAY [  6.370s]
Writing 'product_a'                                OKAY [  0.215s]
Sending sparse 'product_a' 2/2 (20144 KB)          OKAY [  0.491s]
Writing 'product_a'                                OKAY [  0.033s]
Finished. Total time: 7.116s
Sending 'vbmeta_system_a' (4 KB)                   OKAY [  0.000s]
Writing 'vbmeta_system_a'                          OKAY [  0.002s]
Finished. Total time: 0.005s
Resizing 'system_ext_a'                            OKAY [  0.003s]
Sending sparse 'system_ext_a' 1/2 (262140 KB)      OKAY [  6.388s]
Writing 'system_ext_a'                             OKAY [  0.288s]
Sending sparse 'system_ext_a' 2/2 (206196 KB)      OKAY [  5.036s]
Writing 'system_ext_a'                             OKAY [  0.164s]
Finished. Total time: 11.884s
Sending 'vendor_boot_a' (98304 KB)                 OKAY [  2.385s]
Writing 'vendor_boot_a'                            OKAY [  0.115s]
Finished. Total time: 2.504s
fastboot: error: cannot load 'out/target/product/pdx234/vendor_dlkm.img': No such file or directory
```

**Comment by gecko19** [comment]
Hello @jerpelea. It does work now as expected. Though it it did take a couple of boots to show the screen. Thanks a lot for your help on this.
